# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-05 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
